# 适配 SUES-200 的特征路径
feat_root: '/root/autodl-tmp/0-pipei-dinov3/feats_sues/dinov3_vith16plus'
output_dir: '/root/autodl-tmp/0-pipei-dinov3/outputs/sues_unsupervised_srdae_512'
save_name: 'srdae_model_23_26_29.pth'

# 融合层配置 (推荐配置)
fusion_layers: [23, 26, 29] 
# 1280 * 3 = 3840
input_dim: 3840
latent_dim: 1280

train:
  batch_size: 1024
  epochs: 60
  lr: 0.001
  warmup_epochs: 5
  drop_rate: 0.0      
  
  # # Loss Balancing (保持您的 V12 配置)
  # lambda_recon: 1.0
  # lambda_decov: 80.0   
  # lambda_orth: 5.0     
  # lambda_sparse: 0.05

  # Loss Balancing (保持您的 V12 配置)
  lambda_recon: 0.5
  lambda_decov: 100.0   
  lambda_orth: 10.0     
  lambda_sparse: 0.001